### ISSUE TITLE
val3_driver: readme needs to be updated after merge into main repository

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/staubli_experimental#13]
The [current version](https://github.com/ros-industrial/staubli_experimental/blob/f2259556476990aae2d5340daa60484bad38d871/staubli_val3_driver/README.md) of `README.md` needs to be updated:
- refers to non-existent directory: `val3_driver`
- instructs user to clone from `ocadotechnology` fork instead of main repository
- refers to non-existent `val3_server-devel` branch

**Comment by gavanderhoorn** [comment]
@MuriloMartins: do you think you can take care of this one? Use of this repository is increasing, and I'd rather people clone the main repository than the `ocadotechnology` fork (fi).

**Comment by MuriloMartins** [comment]
@gavanderhoorn please see PR #17.

**Comment by gavanderhoorn** [comment]
Fixed in #17.

**Comment by gavanderhoorn** [comment]
Thanks @MuriloMartins for the fix.

Bit early, but: :beers: :)

**Comment by MuriloMartins** [comment]
:+1:
