### ISSUE TITLE
MoveIt packages for the tx60 and tx90 series

### ISSUE THREAD

**Issue by nilsmelchert** [ros-industrial/staubli_experimental#23]
Are there any guidelines besides [this](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot) one about how the MoveIt packages for robots in ROS-I should look like? 
In [staubli](https://github.com/ros-industrial/staubli) there are already MoveIt packages for the tx160 series available. Should they also be created for the tx90 and tx60 series?

**Comment by gavanderhoorn** [comment]
@nilsmelchert wrote:
> Are there any guidelines besides [this](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot) one about how the MoveIt packages for robots in ROS-I should look like? 

No, that is (unfortunately) the only document giving some hints at the moment.

I would recommend to mimic the configuration of the RX160 closely.

> In [staubli](https://github.com/ros-industrial/staubli) there are already MoveIt packages for the tx160 series available. Should they also be created for the tx90 and tx60 series?

We could definitely add some for those series as well. The reason we've been hesitant in the past with this is that we don't expect a lot of people to actually reuse MoveIt packages: you would have to either create a new one if you're setting things up for *your* robot in *your* robot cell, or start editing the one that is provided by a repository.

If users are creating a new one anyway, it doesn't make much sense for us to create and maintain one here in the repository. Editing could be an option, but if we ever release the MoveIt configurations, they would be located in non-world-writable locations, which makes editing impossible.
