### ISSUE TITLE
TX40 gazebo

### ISSUE THREAD

**Issue by iamnotedible** [ros-industrial/staubli_experimental#50]
Hi all,

Is the model for Staubli TX40 available in gazebo?
@johnwason

**Comment by gavanderhoorn** [comment]
All the packages we have here are what you can see in the repository (and in `ros-industrial/staubli`).

So no, right now we don't have a support package nor Gazebo support for the TX40 here.

**Comment by gavanderhoorn** [comment]
I just remembered I had seen at least a support package somewhere recently, and found it: [Tomiliat/Staubli_backup/staubli_ws/src/staubli_tx40_support](https://github.com/Tomiliat/Staubli_backup/tree/0932e66c12cec5fc2774c96f63d895cdcdeb9b07/staubli_ws/src/staubli_tx40_support).

Note: I haven't used this myself, nor have I verified it is correct.

I cannot say anything about the state of it.

**Comment by iamnotedible** [comment]
@gavanderhoorn 
Thanks for pointing it out, I'll try it out.

**Comment by gavanderhoorn** [comment]
@hehonglu123: what was the conclusion here?

**Comment by iamnotedible** [comment]
The urdf seems to have collision problem on my side in gazebo, it loads fine after I commenting out the collision element. It can be loaded to tesseract with collision element directly.

**Comment by iamnotedible** [comment]
I just found out it doesn't quite look like the actual tx40, and the model is always spawned in the world center and not able to drag it around. 
![staubli_tess](https://user-images.githubusercontent.com/44752310/82092547-7ee7cc00-96c7-11ea-8681-b8df1fc1dff6.png)
![Screenshot from 2020-05-15 16-18-01](https://user-images.githubusercontent.com/44752310/82092632-aa6ab680-96c7-11ea-994d-b4353c9e308a.png)

**Comment by gavanderhoorn** [comment]
That doens't look good, no.

Seems you'll have to create the support package yourself then.

thanks for letting us know.

**Comment by gavanderhoorn** [comment]
Oh and if you do end up creating a support package for the TX40, please consider submitting a PR to add it here to the repository.

**Comment by SinaMirrazavi** [comment]
There is a normal version which be found here:
https://github.com/Tomiliat/Staubli_backup/tree/master/staubli_ws/src/staubli_tx40_support/meshes/visual/normal
I don't know how accurate the model is , but .stl files seem visually fine.
