### ISSUE TITLE
Missing staubli_rx160_support?

### ISSUE THREAD

**Issue by Avdbergnmf** [ros-industrial/staubli_experimental#51]
The staubli_rx160_support pkg seems to be missing, or am I the one missing something?

**Comment by gavanderhoorn** [comment]
You've probably not seen [ros-industrial/staubli/staubli_rx160_support](https://github.com/ros-industrial/staubli/tree/f58f43cb55f7c9afe5b35e1e299b2aec06cec14a/staubli_rx160_support)?

**Comment by Avdbergnmf** [comment]
Perfect, thank you. And excuse me for not finding that sooner!

**Comment by gavanderhoorn** [comment]
No need to apologise.
