### ISSUE TITLE
support for gazebo with tx2_60_description

### ISSUE THREAD

**Issue by idarren-deng** [ros-industrial/staubli_experimental#58]
inertial is missing in urdf, the model can not be imported into gazebo.
Error will be " This robot has a joint named "tx2_60_joint_1" which is not in the gazebo model."
Could not initialize robot simulation interface

**Comment by gavanderhoorn** [comment]
Probably due to the fact the `_macro.xacro`s don't contain any `inertial` elements.

Gazebo tends to lump `link`s without those elements together, and ignores `joint`s without `dynamics` elements.

You'd have to add those.
